Add issues:write permission to broken links GHA
The issue reporting step of the Markdown broken link check GitHub Action
is failing due to missing permissions.

> Error: Resource not accessible by integration

Signed-off-by: Daniel Farrell <dfarrell@redhat.com>